# Generated by Django 4.2.16 on 2025-06-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voterecord",
            unique_together={("vote_number", "parliament")},
        ),
    ]
