# Generated by Django 4.2.16 on 2025-06-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_voterecord_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voterecord",
            name="vote_number",
            field=models.IntegerField(db_index=True),
        ),
    ]
