# Generated by Django 4.2.16 on 2025-06-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_voterecord_vote_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="unique_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["unique_hash"], name="core_bill_unique__ed34e7_idx"
            ),
        ),
    ]
