# Generated by Django 4.2.16 on 2025-06-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_bill_unique_hash_bill_core_bill_unique__ed34e7_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bill",
            name="core_bill_unique__ed34e7_idx",
        ),
        migrations.AlterUniqueTogether(
            name="bill",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="bill",
            name="unique_hash",
        ),
    ]
