# Generated by Django 4.2.16 on 2025-06-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_bill_core_bill_unique__ed34e7_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voterecord",
            unique_together=set(),
        ),
    ]
