# Generated by Django 4.2.16 on 2025-06-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_voterecord_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voterecord",
            unique_together={("vote_number", "parliament", "session")},
        ),
    ]
