# Generated by Django 4.2.16 on 2025-06-16 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_voterecord_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="committee",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="committee",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="parliament",
        ),
    ]
