# Generated by Django 4.2.16 on 2025-06-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_committee_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpvote",
            name="parliament",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.parliament",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mpvote",
            name="session",
            field=models.IntegerField(default=1),
        ),
    ]
