# Generated by Django 4.2.16 on 2025-06-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_mpvote_parliament_mpvote_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="voterecord",
            name="absent_count",
            field=models.IntegerField(default=0),
        ),
    ]
